### ISSUE TITLE
Blobs vs. ArrayBuffers

### ISSUE THREAD

**Issue by domenic** [domenic/streaming-mediastreams#5]
It would be good to explicitly spell out the reason for choosing `Blob`s instead of `ArrayBuffer`s. If the data is going to be kept in-memory anyway, `ArrayBuffer`s seems like a better choice. They allow author access and manipulation of the data on a lower level, without jumping through `FileReader`-based hoops.

**Comment by martinthomson** [comment]
I believe that the main reason for using a blob is that the data is not in-memory.  It might be in a buffer in the graphics subsystem somewhere.

**Comment by domenic** [comment]
Ah fascinating! So not the usual blobs-for-things-on-disk approach, but instead blobs-for-things-in-a-different-region-of-memory approach. That makes sense. I wonder if implementers actually use that flexibility.

**Comment by martinthomson** [comment]
Firefox media is built on that design.  All media sits elsewhere, and access to it from the main thread are always asynchronous dispatches to the media subsystem.

**Comment by domenic** [comment]
Oh excellent! I'll add a note about this to the doc to close this out. Thanks very much for the info.
